services:
  db:
    image: postgres:17-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: go_cloud_native
      POSTGRES_USER: gouser
      POSTGRES_PASSWORD: go123
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
